name: gh

on:
  push:
    paths:
      - ".github/workflows/gh.yml"
      - "gh/**"
  workflow_dispatch: # manual

jobs:
    cli:
        runs-on: ubuntu-latest
        steps:
            - run: env
            - run: gh --version
            - run: gh repo list
            - run: gh issue list
            - run: gh workflow list
            - run: gh api /repos/:owner/:repo/actions/workflows